export const DATASTREAM_EVENT_TYPES = [
  "artifact.created",
  "artifact.reconciled",
  "billing.budget.threshold_reached",
  "billing.auto_topup.failed",
  "billing.auto_topup.action_required",
  "filing.published",
  "monitor.match",
  "webhook.test",
  "webhook_endpoint.created",
  "stream_subscription.created",
  "dilution.warrant.created",
  "dilution.convertible.created",
  "dilution.rofr.created",
  "dilution.lockup.created",
  "dilution.corporate_action.created",
  "dilution.reverse_split.created",
  "dilution.nasdaq_compliance.status_changed",
  "intelligence.query.completed",
  "intelligence.query.failed",
  "export.completed",
  "export.failed",
] as const

// Back-compat alias for existing misspelled imports.
export const DATSTREAM_EVENT_TYPES = DATASTREAM_EVENT_TYPES

export type DatastreamEventType = (typeof DATASTREAM_EVENT_TYPES)[number]
export type DatastreamEventCatalogStatus = "public_emitting" | "internal" | "reserved"
export type DatastreamEventBillingFamily = "delivery_events" | "email_notifications" | "non_billable"

export type DatastreamEventCatalogEntry = {
  object: "event_type"
  type: DatastreamEventType
  status: DatastreamEventCatalogStatus
  producer: string
  description: string
  schemaVersion: string
  filterable: boolean
  replaySupport: "event_log" | "manual_only" | "none"
  retention: "plan_default" | "none"
  billingFamily: DatastreamEventBillingFamily
  transports: Array<"webhook" | "stream" | "email">
  samplePayload: Record<string, unknown>
}

const SCHEMA_VERSION = "2026-06-25"

export const DATASTREAM_EVENT_CATALOG: readonly DatastreamEventCatalogEntry[] = [
  {
    object: "event_type",
    type: "artifact.created",
    status: "public_emitting",
    producer: "artifacts_api",
    description: "An artifact generation job completed and produced a manifest.",
    schemaVersion: SCHEMA_VERSION,
    filterable: true,
    replaySupport: "event_log",
    retention: "plan_default",
    billingFamily: "delivery_events",
    transports: ["webhook", "stream"],
    samplePayload: { artifactId: "art_123", kind: "filing_section", status: "ready" },
  },
  {
    object: "event_type",
    type: "artifact.reconciled",
    status: "public_emitting",
    producer: "artifacts_api",
    description: "An artifact reconciliation run updated an artifact manifest.",
    schemaVersion: SCHEMA_VERSION,
    filterable: true,
    replaySupport: "event_log",
    retention: "plan_default",
    billingFamily: "delivery_events",
    transports: ["webhook", "stream"],
    samplePayload: { artifactId: "art_123", status: "reconciled" },
  },
  {
    object: "event_type",
    type: "billing.budget.threshold_reached",
    status: "public_emitting",
    producer: "billing_budget_gate",
    description: "An organization crossed a configured billing budget threshold.",
    schemaVersion: SCHEMA_VERSION,
    filterable: true,
    replaySupport: "event_log",
    retention: "plan_default",
    billingFamily: "delivery_events",
    transports: ["webhook", "stream"],
    samplePayload: { budgetState: "approval_required", usedUsd: 25, thresholdUsd: 25 },
  },
  {
    object: "event_type",
    type: "billing.auto_topup.failed",
    status: "public_emitting",
    producer: "auto_topup",
    description: "An automatic prepaid-credit top-up failed after payment-method fallback.",
    schemaVersion: SCHEMA_VERSION,
    filterable: true,
    replaySupport: "event_log",
    retention: "plan_default",
    billingFamily: "delivery_events",
    transports: ["webhook", "stream"],
    samplePayload: { topupUsd: 50, failureReason: "payment_failed" },
  },
  {
    object: "event_type",
    type: "billing.auto_topup.action_required",
    status: "public_emitting",
    producer: "auto_topup",
    description: "An automatic prepaid-credit top-up requires customer payment action.",
    schemaVersion: SCHEMA_VERSION,
    filterable: true,
    replaySupport: "event_log",
    retention: "plan_default",
    billingFamily: "delivery_events",
    transports: ["webhook", "stream"],
    samplePayload: { topupUsd: 50, actionRequired: true },
  },
  {
    object: "event_type",
    type: "filing.published",
    status: "reserved",
    producer: "filing_ingest",
    description: "Reserved for new filing publication fanout after producer rollout.",
    schemaVersion: SCHEMA_VERSION,
    filterable: true,
    replaySupport: "manual_only",
    retention: "plan_default",
    billingFamily: "delivery_events",
    transports: ["webhook", "stream"],
    samplePayload: { accessionNumber: "0000320193-26-000001", ticker: "AAPL", form: "10-K" },
  },
  {
    object: "event_type",
    type: "monitor.match",
    status: "public_emitting",
    producer: "monitor_dispatch",
    description: "A customer monitor matched new SEC data.",
    schemaVersion: SCHEMA_VERSION,
    filterable: true,
    replaySupport: "event_log",
    retention: "plan_default",
    billingFamily: "delivery_events",
    transports: ["webhook", "stream", "email"],
    samplePayload: { monitorId: "mon_123", matchCount: 1 },
  },
  {
    object: "event_type",
    type: "webhook.test",
    status: "public_emitting",
    producer: "delivery_api",
    description: "A customer-triggered test event for validating webhook signatures and delivery plumbing.",
    schemaVersion: SCHEMA_VERSION,
    filterable: true,
    replaySupport: "event_log",
    retention: "plan_default",
    billingFamily: "delivery_events",
    transports: ["webhook", "stream"],
    samplePayload: { message: "SEC API webhook test", requestedBy: "dashboard" },
  },
  {
    object: "event_type",
    type: "webhook_endpoint.created",
    status: "public_emitting",
    producer: "delivery_api",
    description: "A webhook endpoint was created.",
    schemaVersion: SCHEMA_VERSION,
    filterable: true,
    replaySupport: "event_log",
    retention: "plan_default",
    billingFamily: "delivery_events",
    transports: ["webhook", "stream"],
    samplePayload: { webhookId: "we_123", subscribedEventTypes: ["monitor.match"] },
  },
  {
    object: "event_type",
    type: "stream_subscription.created",
    status: "public_emitting",
    producer: "delivery_api",
    description: "A stream subscription was created.",
    schemaVersion: SCHEMA_VERSION,
    filterable: true,
    replaySupport: "event_log",
    retention: "plan_default",
    billingFamily: "delivery_events",
    transports: ["webhook", "stream"],
    samplePayload: { streamId: "str_123", eventTypes: ["monitor.match"], transport: "poll" },
  },
  {
    object: "event_type",
    type: "dilution.warrant.created",
    status: "reserved",
    producer: "dilution_pipeline",
    description: "Reserved for warrant extraction events once the producer is public.",
    schemaVersion: SCHEMA_VERSION,
    filterable: true,
    replaySupport: "manual_only",
    retention: "plan_default",
    billingFamily: "delivery_events",
    transports: ["webhook", "stream"],
    samplePayload: { ticker: "ABCD", instrumentId: "warrant_123" },
  },
  {
    object: "event_type",
    type: "dilution.convertible.created",
    status: "reserved",
    producer: "dilution_pipeline",
    description: "Reserved for convertible-security extraction events once the producer is public.",
    schemaVersion: SCHEMA_VERSION,
    filterable: true,
    replaySupport: "manual_only",
    retention: "plan_default",
    billingFamily: "delivery_events",
    transports: ["webhook", "stream"],
    samplePayload: { ticker: "ABCD", instrumentId: "convertible_123" },
  },
  {
    object: "event_type",
    type: "dilution.rofr.created",
    status: "reserved",
    producer: "dilution_pipeline",
    description: "Reserved for rights-of-first-refusal extraction events once the producer is public.",
    schemaVersion: SCHEMA_VERSION,
    filterable: true,
    replaySupport: "manual_only",
    retention: "plan_default",
    billingFamily: "delivery_events",
    transports: ["webhook", "stream"],
    samplePayload: { ticker: "ABCD", rightId: "rofr_123" },
  },
  {
    object: "event_type",
    type: "dilution.lockup.created",
    status: "reserved",
    producer: "dilution_pipeline",
    description: "Reserved for lock-up extraction events once the producer is public.",
    schemaVersion: SCHEMA_VERSION,
    filterable: true,
    replaySupport: "manual_only",
    retention: "plan_default",
    billingFamily: "delivery_events",
    transports: ["webhook", "stream"],
    samplePayload: { ticker: "ABCD", lockupId: "lockup_123" },
  },
  {
    object: "event_type",
    type: "dilution.corporate_action.created",
    status: "reserved",
    producer: "dilution_pipeline",
    description: "Reserved for dilution-relevant corporate-action events once the producer is public.",
    schemaVersion: SCHEMA_VERSION,
    filterable: true,
    replaySupport: "manual_only",
    retention: "plan_default",
    billingFamily: "delivery_events",
    transports: ["webhook", "stream"],
    samplePayload: { ticker: "ABCD", actionType: "reverse_split" },
  },
  {
    object: "event_type",
    type: "dilution.reverse_split.created",
    status: "reserved",
    producer: "dilution_pipeline",
    description: "Reserved for reverse-split events once the producer is public.",
    schemaVersion: SCHEMA_VERSION,
    filterable: true,
    replaySupport: "manual_only",
    retention: "plan_default",
    billingFamily: "delivery_events",
    transports: ["webhook", "stream"],
    samplePayload: { ticker: "ABCD", ratio: "1-for-10" },
  },
  {
    object: "event_type",
    type: "dilution.nasdaq_compliance.status_changed",
    status: "reserved",
    producer: "dilution_pipeline",
    description: "Reserved for Nasdaq-compliance status transition events once the producer is public.",
    schemaVersion: SCHEMA_VERSION,
    filterable: true,
    replaySupport: "manual_only",
    retention: "plan_default",
    billingFamily: "delivery_events",
    transports: ["webhook", "stream"],
    samplePayload: { ticker: "ABCD", previousStatus: "notice", currentStatus: "cured" },
  },
  {
    object: "event_type",
    type: "intelligence.query.completed",
    status: "public_emitting",
    producer: "intelligence_api",
    description: "An async intelligence query job finished successfully. Replaces polling /v1/intelligence/query/{jobId}.",
    schemaVersion: SCHEMA_VERSION,
    filterable: true,
    replaySupport: "event_log",
    retention: "plan_default",
    billingFamily: "delivery_events",
    transports: ["webhook", "stream"],
    samplePayload: { jobId: "job_123", status: "completed", intent: "company_due_diligence", artifactId: "art_456" },
  },
  {
    object: "event_type",
    type: "intelligence.query.failed",
    status: "public_emitting",
    producer: "intelligence_api",
    description: "An async intelligence query job terminated with an error.",
    schemaVersion: SCHEMA_VERSION,
    filterable: true,
    replaySupport: "event_log",
    retention: "plan_default",
    billingFamily: "delivery_events",
    transports: ["webhook", "stream"],
    samplePayload: { jobId: "job_123", status: "failed", errorText: "execution failed" },
  },
  {
    object: "event_type",
    type: "export.completed",
    status: "public_emitting",
    producer: "exports_api",
    description: "An async bulk export job finished and a signed download URL is available.",
    schemaVersion: SCHEMA_VERSION,
    filterable: true,
    replaySupport: "event_log",
    retention: "plan_default",
    billingFamily: "delivery_events",
    transports: ["webhook", "stream"],
    samplePayload: { jobId: "exp_123", status: "completed", downloadUrl: "https://…signed…", expiresAt: "2026-06-30T00:15:00Z" },
  },
  {
    object: "event_type",
    type: "export.failed",
    status: "public_emitting",
    producer: "exports_api",
    description: "An async bulk export job terminated with an error.",
    schemaVersion: SCHEMA_VERSION,
    filterable: true,
    replaySupport: "event_log",
    retention: "plan_default",
    billingFamily: "delivery_events",
    transports: ["webhook", "stream"],
    samplePayload: { jobId: "exp_123", status: "failed", errorText: "export failed" },
  },
]

export function listDatastreamEventCatalog(status?: DatastreamEventCatalogStatus | null) {
  return status ? DATASTREAM_EVENT_CATALOG.filter((entry) => entry.status === status) : DATASTREAM_EVENT_CATALOG
}

export function getDatastreamEventCatalogEntry(type: string) {
  return DATASTREAM_EVENT_CATALOG.find((entry) => entry.type === type) ?? null
}
